### ISSUE TITLE
Region class without attribute magnitude

### ISSUE THREAD

**Issue by khawajasim** [SCECcode/pycsep#124]
I noticed that in class CartesianGrid2D, the attribute of magnitudes (mag bins) is not initialized in constructor. I was thinking, if a user creates region class without providing magnitude attribute, then it will lead to an error while running a test. I was thinking, why not initialize it in constructor and bind a user to provides magnitudes or have a default value. 
What do you think about it?

PS: I did the same with Quadtree region class for now. I would follow the same idea as you propose about this. 

Cheers.

**Comment by wsavran** [comment]
hi @khawajasim, sorry i didn't respond to this issue on here any sooner. im remembering we discussed this on a call and came to the conclusion that we should implement a class that contains both a magnitude component and the spatial component `SpaceMagnitudeRegion` or something of this sort. 

i think we make this a development target for later down the road as people can use the `create_space_magnitude_region` function to properly add magnitude bins to the spatial class. 

i'm closing this issue for now because of our previous conversations, but please re-open if/when you think we should revisit this issue.
