### ISSUE TITLE
Plotting tutorials?

### ISSUE THREAD

**Issue by nvanderelst** [SCECcode/pycsep#164]
I have tried running the tutorials provided, but I think there is a step missing in the downloaded files to get to the images. Without this, or some other output, it is hard to confirm the functionality. I am using python (miniconda3) from the terminal. I'm no expert, but I have used matplotlib before, and am expecting something like a .show() method.

**Comment by nvanderelst** [comment]
I have run into a functionality issue with csep.utils.stats that I do not know how to resolve.

e.g:
"Traceback (most recent call last):
  File "/Users/nvanderelst-local/pyCSEP/gridded_forecast_evaluation.py", line 30, in <module>
    from csep.utils.stats import get_Kagan_I1_score
ImportError: cannot import name 'get_Kagan_I1_score' from 'csep.utils.stats' (/opt/miniconda3/lib/python3.9/site-packages/csep/utils/stats.py)"

and:
"plotting ROC curve
Traceback (most recent call last):
  File "/Users/nvanderelst-local/pyCSEP/catalog_forecast_evaluation.py", line 133, in <module>
    plots.plot_ROC(forecast, comcat_catalog)
AttributeError: module 'csep.utils.plots' has no attribute 'plot_ROC'"

**Comment by wsavran** [comment]
thanks for point out those issues @nvanderelst. the first one is because the outputs are rendered using jupyter notebooks and don't require the plt.show() call to view the figures. michael pointed that out in his review. i'll push a patch to make it clear how to show the plots from the terminal.

the second part looks like its because of a new pull request i merged this week that wasn't included in the v0.5.1 release. you installed via miniconda?

**Comment by nvanderelst** [comment]
Yes, I installed via Miniconda.

**Comment by wsavran** [comment]
@nvanderelst i updated the example scripts to work with the latest conda release. there were some features included in those examples that need an installation from source to run.

**Comment by kbarnhart** [comment]
Linking this to the JOSS review issue.

openjournals/joss-reviews/issues/3658

**Comment by nvanderelst** [comment]
I've been able to get everything to work, now.
