### ISSUE TITLE
Catalog Filter with argument of year range?

### ISSUE THREAD

**Issue by baobaohan** [SCECcode/pycsep#53]
Hi Bill,

I followed the documentation page to explore with the Catalog class and its functions. I try to played with the CSEPCatalog.filter() function but can't do it with any 'year' arguments (like example showed here https://cseptesting.org/reference/generated/csep.core.catalogs.CSEPCatalog.filter.html#csep.core.catalogs.CSEPCatalog.filter)

![Screen Shot 2020-11-04 at 2 42 20 PM](https://user-images.githubusercontent.com/33332247/98175710-f85cbc00-1eab-11eb-9271-b84960e2f4dd.png)

Han

**Comment by wsavran** [comment]
Thanks again for catching antoher issue in the documentation. This docstring is from a legacy format where the year was specified (also related to the issue you had with the .ndk reader).

If you want to filter by year, you will have to use the full datetime string. You can follow the example [here](https://cseptesting.org/tutorials/catalog_filtering.html) to filter the catalog by year. 

You can also filter using datetime objects instead of coverting to integer years. There are some documentation provided for this [here](https://cseptesting.org/concepts/catalogs.html#filtering-events)

Let me know if you have any other issues with this

**Comment by wsavran** [comment]
I'm leaving this issue open until I update the docstring you found

**Comment by baobaohan** [comment]
Thanks, Bill. I just tried both of the epoch time method and datetime-object method. All work smoothly. 

Again, thanks for the fast reply. Really appreciate it.

**Comment by baobaohan** [comment]
I think I found a small bug when trying to use datatime object to filter a time range.

Having two datetime arguments (one 'greater than' and the other 'less than') won't do the job but only follow the second restriction. (see the screeshot)

The epoch time method of filter works fine. Hope it helps.

![Screen Shot 2020-11-04 at 3 47 27 PM](https://user-images.githubusercontent.com/33332247/98180150-1da1f800-1eb5-11eb-9a96-118efc086330.png)

**Comment by wsavran** [comment]
ill look into this. are you saying this works properly with the origin_time, but not the datetime argument?

**Comment by baobaohan** [comment]
Yes, Bill. No rush at all since I've done what I need using the 'origin_time' argument.

**Comment by wsavran** [comment]
great, im working on a fix for this. strangely, this seemed to be addressed by #36 but the unit tests did not actually apply an assert statement. ill write back here when this issue is fixed.
